### ISSUE TITLE
Raspberry Pi Zero Error Message

### ISSUE THREAD

**Issue by rei-vilo** [shmuelzon/ble2mqtt#1]
I've installed `ble2mqtt` on a Raspberry Pi Zero with Raspbian.

Launching `node app.js` throws the following error:

>
>$ node app.js
>/home/pi/.node-red/ble2mqtt/app.js:58
>  return _(list).find(item => str.search(item) !== -1) ? action : !action;
>                           ^^
SyntaxError: Unexpected token =>
>    at exports.runInThisContext (vm.js:73:16)
>    at Module._compile (module.js:443:25)
>    at Object.Module._extensions..js (module.js:478:10)
>    at Module.load (module.js:355:32)
>    at Function.Module._load (module.js:310:12)
>    at Function.Module.runMain (module.js:501:10)
>    at startup (node.js:129:16)
>    at node.js:814:3
>

**Comment by shmuelzon** [comment]
I think you need to update node to a newer version that supports arrow functions.
You'll also need a newer version of Bluez than the one supplied with Raspbian.
Regardless, you should start the app with `npm start` since it will also downloads the latest GATT definitions from bluetooth.org.

**Comment by shmuelzon** [comment]
Here are some of my notes when installing the app on an RPi 3:

``` bash
# Allow tabs to be tabs (for patches and configuration files)
bind '\C-i:self-insert'

# Get dependencies
sudo apt-get update
sudo apt-get install -y libusb-dev libdbus-1-dev libglib2.0-dev libudev-dev \
  libical-dev libreadline-dev checkinstall git python3-pip screen nginx \
  libavahi-compat-libdnssd-dev mosquitto

# Compile + Install Bluez 5.40
mkdir ~Downloads
wget -O ~/Downloads/bluez-5.40.tar.xz http://www.kernel.org/pub/linux/bluetooth/bluez-5.40.tar.xz
mkdir ~/code
cd ~/code
tar -xvf bluez-5.40.tar.xz
cd bluez-5.40

patch -p1 << EOF
--- a/tools/hciattach.c
+++ b/tools/hciattach.c
@@ -1236,7 +1236,7 @@
 {
    struct uart_t *u = NULL;
    int detach, printpid, raw, opt, i, n, ld, err;
-   int to = 10;
+   int to = 30;
    int init_speed = 0;
    int send_break = 0;
    pid_t pid;
--- a/tools/hciattach_bcm43xx.c
+++ b/tools/hciattach_bcm43xx.c
@@ -43,7 +43,7 @@
 #include "hciattach.h"

 #ifndef FIRMWARE_DIR
-#define FIRMWARE_DIR "/etc/firmware"
+#define FIRMWARE_DIR "/lib/firmware"
 #endif

 #define FW_EXT ".hcd"
@@ -366,11 +366,8 @@
        return -1;

    if (bcm43xx_locate_patch(FIRMWARE_DIR, chip_name, fw_path)) {
-       fprintf(stderr, "Patch not found, continue anyway\n");
+       fprintf(stderr, "Patch not found for %s, continue anyway\n", chip_name);
    } else {
-       if (bcm43xx_set_speed(fd, ti, speed))
-           return -1;
-
        if (bcm43xx_load_firmware(fd, fw_path))
            return -1;

@@ -380,6 +377,7 @@
            return -1;
        }

+       sleep(1);
        if (bcm43xx_reset(fd))
            return -1;
    }
--- a/src/bluetooth.conf
+++ b/src/bluetooth.conf
@@ -34,6 +34,10 @@
     <allow send_destination="org.bluez"/>
   </policy>

+  <policy group="bluetooth">
+    <allow send_destination="org.bluez"/>
+  </policy>
+
   <policy context="default">
     <deny send_destination="org.bluez"/>
   </policy>
--- a/src/bluetooth.service.in
+++ b/src/bluetooth.service.in
@@ -6,7 +6,7 @@
 [Service]
 Type=dbus
 BusName=org.bluez
-ExecStart=@libexecdir@/bluetoothd
+ExecStart=@libexecdir@/bluetoothd -E
 NotifyAccess=main
 #WatchdogSec=10
 #Restart=on-failure
EOF


./configure --disable-cups --disable-obex --prefix=/usr --libexecdir=/usr/lib --localstatedir=/var/lib/bluetooth/
make -j 4
sudo checkinstall -y --nodoc --maintainer=shmuelzon@gmail.com

# Install Node
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

I needed the newer bluez (with Raspbian modifications) as a Debian package since the RPi 3 has its own package (`pi-bluetooth`) that adds the hci device that depends on the bluez package. Not sure if its needed to the Zero, but it's still here. Should probably add a wiki or something for that.

**Comment by shmuelzon** [comment]
BTW - It should also be possible (and probably simpler) to point your RPi to the stretch (testing) APT repo instead of jessie (stable) in /etc/apt/sources.list. You'll get newer versions of Node and Bluez which should support everything needed to run this app.

I'm closing this issue for now as I haven't heard back from you.

**Comment by rei-vilo** [comment]
Thank you for the pointers. They did the trick!

**Comment by shmuelzon** [comment]
Glad to hear you got it working. Let me know if you have any insights you can share.
