### ISSUE TITLE
connect to mqtt

### ISSUE THREAD

**Issue by Yury777** [shmuelzon/ble2mqtt#3]
Hello!
I installed mosquitto. Each client has a password. How to write in config.json login and password?

**Comment by shmuelzon** [comment]
Just add the `username` and `password` fields to the config.json file inside the `mqtt.server` object.

**Comment by Yury777** [comment]
my config.json:
{
  "mqtt": {
    "server": {
      "host": "127.0.0.1",
      "port": 1883
    },
    "publish": {
      "retain": true
    },
    "topics" :{
      "device_name": "Address",
      "set_suffix": "/Set"
    }
  },
  "ble": {
    "services": { },
    "characteristics": { }
  }
}

**Comment by Yury777** [comment]
the service is not working :-(
log:
● ble2mqtt@root.service - BLE2MQTT Bridge for root
   Loaded: loaded (/etc/systemd/system/ble2mqtt@root.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2018-11-27 17:46:56 +07; 4s ago
  Process: 2086 ExecStart=/usr/bin/npm start (code=exited, status=1/FAILURE)
 Main PID: 2086 (code=exited, status=1/FAILURE)

ноя 27 17:46:56 raspberrypi systemd[1]: ble2mqtt@root.service: Unit entered failed state.
ноя 27 17:46:56 raspberrypi systemd[1]: ble2mqtt@root.service: Failed with result 'exit-code'.
ноя 27 17:46:56 raspberrypi systemd[1]: ble2mqtt@root.service: Service hold-off time over, scheduling restart.
ноя 27 17:46:56 raspberrypi systemd[1]: Stopped BLE2MQTT Bridge for root.
ноя 27 17:46:56 raspberrypi systemd[1]: ble2mqtt@root.service: Start request repeated too quickly.
ноя 27 17:46:56 raspberrypi systemd[1]: Failed to start BLE2MQTT Bridge for root.
ноя 27 17:46:56 raspberrypi systemd[1]: ble2mqtt@root.service: Unit entered failed state.
ноя 27 17:46:56 raspberrypi systemd[1]: ble2mqtt@root.service: Failed with result 'exit-code'.

**Comment by Yury777** [comment]
can you show your config.json for example?

**Comment by shmuelzon** [comment]
The error shown doesn't seem related to the configuration file as the app fails to load.
Can you please post the results of `sudo journalctl -u ble2mqtt@root.service` or simple run `npm start` in the directory where you downloaded the application?

BTW - you didn't add the username and password to the configuration file. it should be right next to the `host` and `port` fields.

**Comment by Yury777** [comment]
sudo journalctl -u ble2mqtt@root.service:
ноя 27 17:40:40 raspberrypi systemd[1]: Started BLE2MQTT Bridge for root.
ноя 27 17:40:40 raspberrypi systemd[1]: ble2mqtt@root.service: Main process exited, code=exited, status=210/CHROOT
ноя 27 17:40:40 raspberrypi systemd[1]: ble2mqtt@root.service: Unit entered failed state.
ноя 27 17:40:40 raspberrypi systemd[1]: ble2mqtt@root.service: Failed with result 'exit-code'.
ноя 27 17:40:40 raspberrypi systemd[1]: ble2mqtt@root.service: Service hold-off time over, scheduling restart.
ноя 27 17:40:40 raspberrypi systemd[1]: Stopped BLE2MQTT Bridge for root.

**Comment by Yury777** [comment]
npm start:
> ble2mqtt@1.0.0 prestart /root/ble2mqtt
> node utils/getGattAssignedNumbers.js

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/ble2mqtt/utils/getGattAssignedNumbers.js:11:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ble2mqtt@1.0.0 prestart: `node utils/getGattAssignedNumbers.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ble2mqtt@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-27T11_16_19_650Z-debug.log

**Comment by shmuelzon** [comment]
Did you execute `npm install` is the source directory in order to download and install the dependencies?

**Comment by Yury777** [comment]
apt-get update
curl -sL https://deb.nodesource.com/setup_6.x | bash -
apt-get install bluetooth bluez libbluetooth-dev libudev-dev nodejs
cd /root
git clone https://github.com/shmuelzon/ble2mqtt
cd ble2mqtt
npm install

make file: /etc/systemd/system/ble2mqtt@root.service
[Unit]
Description=BLE2MQTT Bridge for root
After=network.target bluetooth.service

[Service]
Type=simple
WorkingDirectory=/root/ble2mqtt
ExecStart=/usr/bin/npm start
User=root
SendSIGKILL=no
Restart=on-failure

[Install]
WantedBy=multi-user.target
------------------

sudo systemctl daemon-reload
sudo systemctl enable ble2mqtt@root.service
sudo systemctl start ble2mqtt@root.service

**Comment by shmuelzon** [comment]
And did `npm install` exit successfully? It seems the debug library is missing.

**Comment by Yury777** [comment]
root@raspberrypi:~/ble2mqtt# npm install
(node:19912) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

> dbus@0.2.19 install /root/ble2mqtt/node_modules/dbus
> node-gyp configure build

Package dbus-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `dbus-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'dbus-1' found
gyp: Call to 'pkg-config  --libs-only-l --libs-only-other dbus-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "build"
gyp ERR! cwd /root/ble2mqtt/node_modules/dbus
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! dbus@0.2.19 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dbus@0.2.19 install script.
npm ERR! This is most likely a problem with the dbus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls dbus
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.14.79-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /root/ble2mqtt
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/ble2mqtt/npm-debug.log
npm ERR! not ok code 0

**Comment by shmuelzon** [comment]
Try: `sudo apt-get install libdbus-1-dev`

**Comment by Yury777** [comment]
Thank you!
npm install:
(node:20018) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! cb() never called!
npm ERR! not ok code 0

**Comment by shmuelzon** [comment]
Well, that's obscure... :)
That's the entire output?

**Comment by Yury777** [comment]
yes :-(

**Comment by shmuelzon** [comment]
Maybe remove the node_modules directory and try again?

To be honest, I haven't run this project for quite some time. I'm using the [ESP32](https://github.com/shmuelzon/esp32-ble2mqtt) variant. Cheaper than a RaspberryPi and and more stable.

**Comment by Yury777** [comment]
I have ESP8266 and ESP32 but I got tired of them due to wifi issues. I liked nrf52 better. They're more stable.

**Comment by Yury777** [comment]
nrf52(senor&relay)+raspberry

**Comment by Yury777** [comment]
Hurray! it works!
I reinstalled everything

**Comment by Yury777** [comment]
Please tell me where to add user-password for mqtt?

**Comment by Yury777** [comment]
and where to insert " whitelist": [
  "A0:E6: F8:.*"
]

**Comment by shmuelzon** [comment]
```json
{
  "mqtt": {
    "server": {
      "username": "XXX",
      "password": "YYY",
      "host": "127.0.0.1",
      "port": 1883
    },
    "publish": {
      "retain": true
    },
    "topics" :{
      "device_name": "Address",
      "set_suffix": "/Set"
    }
  },
  "ble": {
    "whitelist": [
      "A0:E6:F8:.*"
    ]
  }
}
```

**Comment by Nieflav** [comment]
> and where to insert " whitelist": [
> "A0:E6: F8:.*"
> ]



> Hurray! it works!
> I reinstalled everything

Hi, could you explain what exactly you have reinstalled ? because i am facing the same issue on ubuntu 18, I reinstalled everything but nothing changed : I still have problems with dbus

Thanks
