### ISSUE TITLE
services & characteristics 

### ISSUE THREAD

**Issue by Yury777** [shmuelzon/ble2mqtt#5]
How to insert the entire services and characteristics directory from http://www.bluetooth.org to ble2mqtt?

**Comment by Yury777** [comment]
Maybe it used to work automatically, and after changing the URL, it broke...
old url = https://developer.bluetooth.org/gatt/services/Pages/ServiceViewer.aspx?u=org.bluetooth.service.battery_service.xml
new url = https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.service.battery_service.xml

**Comment by shmuelzon** [comment]
Should be fixed now. Make sure do delete `resources/*.json` so they will be re-created.
