### ISSUE TITLE
characteristic type

### ISSUE THREAD

**Issue by Yury777** [shmuelzon/ble2mqtt#6]
Hello!
How convert this characteristics to string?
Name | UUID | Type | Data | Description 
Pressure characteristic | 0202 | Notify | 5 bytes | Pressure in hPa: int32_t - integer, uint8_t - decimal
=
Now I receive in mqtt: 216,3,0,0,90. How convert to 1092 hPa? 
I try:
"ef680202-9b35-4933-9b10-52ffa9740042": { "name": "Pressure", "types":  ["uint32"], "types": ["uint8"] },

**Comment by shmuelzon** [comment]
Try this:
```json
{
  "ble": {
    "characteristics": {
      "ef680202-9b35-4933-9b10-52ffa9740042": {
        "name": "Pressure",
        "types": [
          "uint32",
          "uint8"
        ] 
      }
    }
  }
}
```

**Comment by Yury777** [comment]
It's WORKING!!!
Tell me please, how I can convert this data?
Device name characteristic | 0101 | Write/Read | max 10 bytes | Device name as ASCII string.

**Comment by shmuelzon** [comment]
Try this:
```json
{
  "ble": {
    "characteristics": {
      "ef680101-9b35-4933-9b10-52ffa9740042": {
        "name": "Device Name",
        "types": [
          "utf8s"
        ] 
      }
    }
  }
}
```

**Comment by Yury777** [comment]
Thank you!!!
