### ISSUE TITLE
in dev log

### ISSUE THREAD

**Issue by Yury777** [shmuelzon/ble2mqtt#8]
In dev log I see:
 Bluez:Characteristic:/org/bluez/hci0/dev_DA_A6_47_1C_6E_A2/service0055/char0056 Failed reading: Error: org.freedesktop.DBus.Error.UnknownObject +0ms
  Bluez:Characteristic:/org/bluez/hci0/dev_DA_A6_47_1C_6E_A2/service004d/char0051 Failed reading: Error: org.freedesktop.DBus.Error.UnknownObject +0ms
  Bluez:Characteristic:/org/bluez/hci0/dev_DA_A6_47_1C_6E_A2/service002f/char0030 Failed reading: Error: org.freedesktop.DBus.Error.UnknownObject +0ms
  Bluez:Characteristic:/org/bluez/hci0/dev_DA_A6_47_1C_6E_A2/service001d/char002d Failed reading: Error: org.freedesktop.DBus.Error.UnknownObject +1ms

**Comment by shmuelzon** [comment]
Not really much to go on here...
I don't know if the device still exists. Was it disconnected? Did the application get any notification?

Anyways, I've had various D-Bus issues like the above, double notifications and such. I don't know if those were issues with D-Bus, the Node D-Bus package or maybe it was just BlueZ itself. Those problems are what eventually drove me to the ESP32 which is much more stable (and cheaper).
